### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [chosengirl45/prj-rev-bwfs-dasmoto#5]
**GRADE**: Needs Improvement

**SUMMARY**: Great start on this project. The site looks great and you did a good job keeping your code neat and readable throughout. Nice use of divs and classes to help structure and label the content on the page as well!

Behind the scenes, try to always keep in mind DRY principles as you set your styling. Avoid repeating the same styling many times for similarly styled elements wherever possible. Along the same lines, strive to use the most efficient, straight-forward way to accomplish whatever task you're setting out to do. You could likely accomplish the same effect with your background image with one line of css. 

As a next step, try switching over your code to make use of the background-image css property. Reach out to the advisors if you have any questions.

Have fun and keep up the good work!

**Comment by chosengirl45** [comment]
Thank You!!!!
